//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStorageChallange.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryShipmentNoteLine
    {
        public int Factory_Shipment_Note_LineID { get; set; }
        public int Factory_Shipment_Note_HeaderID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public decimal Line_Cost { get; set; }
    
        public virtual FactoryShipmentNoteHeader FactoryShipmentNoteHeader { get; set; }
        public virtual Product Product { get; set; }
    }
}
