//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStorageChallange.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundShipmentHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InboundShipmentHeader()
        {
            this.InboundShipmentLines = new HashSet<InboundShipmentLine>();
        }
    
        public int Inbound_Shipment_HeaderID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboundShipmentLine> InboundShipmentLines { get; set; }
        public virtual Product Product { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
