//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStorageChallange.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.InboundShipmentHeaders = new HashSet<InboundShipmentHeader>();
            this.InboundShipmentLines = new HashSet<InboundShipmentLine>();
            this.FactoryShipmentNoteLines = new HashSet<FactoryShipmentNoteLine>();
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int ProductID { get; set; }
        public string Product_Name { get; set; }
        public decimal Buy_Price { get; set; }
        public decimal Sell_Price { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> Margin_Percent { get; set; }
        public int Quantity_Available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboundShipmentHeader> InboundShipmentHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboundShipmentLine> InboundShipmentLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactoryShipmentNoteLine> FactoryShipmentNoteLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
