//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStorageChallange.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineStoreChallangeDatabaseEntities : DbContext
    {
        public OnlineStoreChallangeDatabaseEntities()
            : base("name=OnlineStoreChallangeDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<OrderHeader> OrderHeaders { get; set; }
        public virtual DbSet<OrderLine> OrderLines { get; set; }
        public virtual DbSet<FactoryShipmentNoteHeader> FactoryShipmentNoteHeaders { get; set; }
        public virtual DbSet<FactoryShipmentNoteLine> FactoryShipmentNoteLines { get; set; }
        public virtual DbSet<InboundShipmentHeader> InboundShipmentHeaders { get; set; }
        public virtual DbSet<InboundShipmentLine> InboundShipmentLines { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
